# Generated by Django 5.0.1 on 2024-03-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
