# Generated by Django 5.0.1 on 2024-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_alter_client_date_created_alter_client_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientLogo',
            field=models.ImageField(default='default_logo.jpg', upload_to='company_logos'),
        ),
    ]
