# Generated by Django 5.0.1 on 2024-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_rename_invoice_product_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='status',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('EMAIL_SENT', 'EMAIL_SENT')], default='CURRENT', max_length=100),
        ),
    ]
